### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by vecos1990** [patrickbryant1/Umol#32]
**Did anyone experience this same error? if yes, what was the workaround approach?**

  File "/homes/cveranso/.conda/envs/Umol2/lib/python3.12/site-packages/numpy/core/_dtype.py", line 143, in _scalar_str
    elif np.issubdtype(dtype, np.number):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homes/cveranso/.conda/envs/Umol2/lib/python3.12/site-packages/numpy/core/numerictypes.py", line 417, in issubdtype
    arg1 = dtype(arg1).type
           ^^^^^^^^^^^
  File "/homes/cveranso/.conda/envs/Umol2/lib/python3.12/site-packages/numpy/core/_dtype.py", line 46, in __repr__
    arg_str = _construction_repr(dtype, include_align=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
**RecursionError: maximum recursion depth exceeded**

Traceback (most recent call last):
  File "/home/disk6/homes/cveranso/Umol/Umol-master/./src/relax/align_ligand_conformer.py", line 192, in <module>
    pred_ligand = read_pdb(args.pred_pdb[0])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/disk6/homes/cveranso/Umol/Umol-master/./src/relax/align_ligand_conformer.py", line 28, in read_pdb
    struc = parser.get_structure('',open(pred_pdb,'r'))
                                    ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/homes/cveranso/Umol/Umol-master/data/test_case/6UWP/6UWP_pred_raw.pdb'

**Comment by patrickbryant1** [comment]
Hi, 

As you can see from the error message, the predicted file is not available. Likely your path is wrong or the previous step failed.
